# Ensure your entrypoints here match what you're exposing on the traefik service on docker-compose-custom1.yml.
entryPoints:
  https-openwebui:
    address: ":8443"
  https-cloudcmd:
    address: ":8143"
  https-dashboard:
    address: ":8080"
  https-pgadmin:
    address: ":8243"

# The docker provider is necessary so that Traefik can analyze Docker service labels
providers:
    docker:
      # However, we only want to expose services that have the traefik.enable=true label
      exposedByDefault: false

# Enable the Traefik dashboard
api:
  dashboard: true

# Define the TLS configuration for Traefik
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /secrets/server_certificate.pem
        keyFile: /secrets/server_key.pem

  certificates:
    - certFile: /secrets/server_certificate.pem
      keyFile: /secrets/server_key.pem
      stores:
        - default